version: '3.9'	

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-todosDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./store/postgres:/var/lib/postgresql/data